# pubspec.yaml  (root of monorepo)
name: sugodride_workspace
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  melos: ^6.3.3    # keep this in sync with the version you want
